config/routes.rb
Nomen::Application.routes.draw do
  filter :locale

  resources :nomenclatures do
    resources :attributes do
    end
    resources :items do
    end
    member do
      get :tree
    end
  end

  root to: 'nomenclatures#index'
end

app/models/nomenclature.rb
# == Schema Information
#
# Table name: nomenclatures
#
#  id            :integer          not null, primary key
#  nomenspace_id :integer
#  property_id   :integer
#  name          :string           not null
#  translateable :boolean          default(FALSE), not null
#  hierarchical  :boolean          default(FALSE), not null
#  state         :string           not null
#  created_at    :datetime
#  updated_at    :datetime
#

class Nomenclature < ActiveRecord::Base
  include Translateable, Checkable
  has_many :property_natures
  has_many :items

  def to_param
    name
  end
end

app/controllers/nomenclatures_controller.rb
# == Schema Information
#
# Table name: nomenclatures
#
#  id            :integer          not null, primary key
#  nomenspace_id :integer
#  property_id   :integer
#  name          :string           not null
#  translateable :boolean          default(FALSE), not null
#  hierarchical  :boolean          default(FALSE), not null
#  state         :string           not null
#  created_at    :datetime
#  updated_at    :datetime
#

require 'csv'

class NomenclaturesController < ApplicationController
  def index
    @nomenclatures = Nomenclature.localized
                                 .includes(property_natures: :choices_nomenclature)
                                 .references(property_natures: :choices_nomenclature)
  end

  def show
    @nomenclature = Nomenclature.find_by(name: params[:id])

    @items = @nomenclature.items.includes(:translations, properties: { choices_nomenclature: { items: :translations } })
  end

  def tree
    @nomenclature = Nomenclature.find_by(name: params[:id])
  end
end

app/views/nomenclatures/_list.html.haml
%ul.item-list
  - items.localized.each do |item|
    %li.item
      %span.item-actions
        - if item.children.any?
          = link_to('#', data: {toggle: 'tree'}) do
            %i.fa.fa-minus-square-o.collapse
            %i.fa.fa-plus-square-o.expand
        - else
          %i.fa.fa-square-o
      %span.item-label= link_to(item.label, nomenclature_item_path(@nomenclature, item))
      - if item.children.any?
        = render 'list', items: item.children

app/views/nomenclatures/_title.html.haml
- title do
  %h1
    = link_to(nomenclatures_path, class: :home) do
      %i
    %span= "/"
    = @nomenclature.label
  %p
    - for format in [:xml, :json, :csv]
      = link_to(format.to_s.upcase, {format: format}, class: "label label-primary")
    - if action_name == 'tree'
      = link_to(nomenclature_path(@nomenclature), class: "label label-primary list") do
        %i
    - else
      = link_to(tree_nomenclature_path(@nomenclature), class: "label label-primary tree") do
        %i

app/views/nomenclatures/index.csv.haml
= raw CSV.generate_line ["Name", "Label", "URI"]
- for nomenclature in @nomenclatures
  = raw CSV.generate_line [nomenclature.name, nomenclature.label, nomenclature_url(nomenclature)]

app/views/nomenclatures/index.html.haml
- title do |default|
  %h1
    -# %i.fa.fa-home
    = "labels.x_nomenclatures".t count: Nomenclature.count
  %p
    - for format in [:xml, :json, :csv]
      = link_to(format.to_s.upcase, {format: format}, class: "label label-primary")

%table.table.table-bordered.table-striped
  %thead
    %tr
      %th= Nomenclature.human_attribute_name(:label)
      %th= Nomenclature.human_attribute_name(:name)
      %th= Nomenclature.human_attribute_name(:items_count)
      -# %th= Nomenclature.human_attribute_name(:description)
  %tbody
    - for nomenclature in @nomenclatures
      %tr
        %td= link_to(nomenclature.label, nomenclature_path(nomenclature))
        %td
          = link_to(nomenclature_path(nomenclature)) do
            = state_icon(nomenclature)
            %strong= nomenclature.name
        %td.decimal= nomenclature.items.count
        -# %td= nomenclature.description

app/views/nomenclatures/show.csv.haml
= raw CSV.generate_line ["Name", "Label"]
- for item in @nomenclature.items
  = raw CSV.generate_line [item.name, item.label]

app/views/nomenclatures/show.html.haml
= render 'title'

= cache [@nomenclature, :list] do
  - property_natures = @nomenclature.property_natures
  %table.table.table-bordered.table-striped
    %thead
      %tr
        %th= Item.human_attribute_name(:label)
        %th= Item.human_attribute_name(:name)
        -# %th= Item.human_attribute_name(:description)
        - property_natures.each do |property_nature|
          %th= property_nature.label
    %tbody
      - @items.each do |item|
        %tr
          %td
            = link_to(nomenclature_item_path(@nomenclature, item)) do
              = item.label
          %td
            = link_to(nomenclature_item_path(@nomenclature, item)) do
              = state_icon(item)
              %strong= item.name
          - property_natures.each do |nature|
            %td
              = human_property(item.properties.detect{ |p| p.nature_id == nature.id }, nature)
          -# %td= item.description

app/views/nomenclatures/tree.html.haml
= render 'title'

= cache [@nomenclature, :tree] do
  .tree= render 'list', items: @nomenclature.items.localized.root